### ISSUE TITLE
StorageElement.test() is broken

### ISSUE THREAD

**Issue by annawoodard** [matz-e/lobster#140]
[Testing](https://github.com/matz-e/lobster/blob/master/lobster/se.py#L78) the storage element is currently broken unless the stageout directory already exists because we call it [before](https://github.com/matz-e/lobster/blob/se-tweaks/lobster/job.py#L52) creating it. This is sort of a chicken-and-egg problem, since we are using the fs module to create the output directory itself. 

It is also broken for Chirp stageout, consider this configuration:
```
storage:
    local: /hadoop/store/user/awoodard/LHE_v14/2d/a/AOD_v1
    input: chirp://earth.crc.nd.edu:9026//
    output: chirp://earth.crc.nd.edu:9026/2d/a/AOD_v1
    base: /hadoop/store/user/awoodard/LHE_v14

tasks:
    - {label: 'ttH', files: '/hadoop/store/user/awoodard/LHE_v14/2d/a/*ttH*/*lhe*'}
```

for which the function calls:
```
chirp earth.crc.nd.edu:9026 ls -la chirp://earth.crc.nd.edu:9026/2d/a/AOD_v1
```
